package vandy.mooc.utils;

import vandy.mooc.common.ParcelableCommand;
import android.net.Uri;
import android.os.Bundle;

/**
 * A ParcelableCommand that's used to play music.
 */
public abstract class ParcelableCommandMusic
       extends ParcelableCommand  {
    /**
     * A UID generated by Eclipse for serialization purposes.
     */
    private static final long serialVersionUID = 10L;

    public static final String SONG_URI =
        "song_uri";
    
    /**
     * Constructor.
     */
    public ParcelableCommandMusic() {
        super();
    }

    /**
     * Factory method that returns a Bundle containing the @a songUri.
     */
    public Bundle makeArgs(Uri songUri) {
        final Bundle args = new Bundle();
        args.putParcelable(SONG_URI, songUri);
        return args;
    }
}
